# Generated by Django 3.0.1 on 2020-03-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Associate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SUPERVISOR', 'SUPERVISOR'), ('VENDOR', 'VENDOR'), ('LABOR', 'LABOR')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('material_name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('CHEAP', 'CHEAP'), ('EXPENSIVE', 'EXPENSIVE')], max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('rate', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('site_type', models.CharField(choices=[('COMMERCIAL', 'COMMERCIAL'), ('OFFICE', 'OFFICE'), ('HOME', 'HOME')], max_length=20)),
                ('source_type', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CHEAP', 'CHEAP'), ('EXPENSIVE', 'EXPENSIVE')], max_length=100)),
                ('service_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('rate_of_service', models.CharField(max_length=20)),
            ],
        ),
    ]
