# Generated by Django 3.0.1 on 2020-03-27 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0002_auto_20200327_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='prospect',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='deal.Prospect'),
        ),
        migrations.AddField(
            model_name='service',
            name='prospect',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='deal.Prospect'),
        ),
    ]
