# Generated by Django 3.0.1 on 2020-03-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0003_auto_20200327_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='complete',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='prospect',
            name='status',
            field=models.CharField(blank=True, choices=[('LEAD', 'LEAD'), ('CLIENT', 'CLIENT'), ('CANCEL', 'CANCEL')], max_length=20),
        ),
    ]
