# Generated by Django 3.0.1 on 2020-03-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=64)),
                ('organization', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mobile_number', models.CharField(default='', max_length=16)),
                ('site_type', models.CharField(choices=[('COMMERCIAL', 'COMMERCIAL'), ('OFFICE', 'OFFICE'), ('HOME', 'HOME')], max_length=100)),
                ('source_type', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], max_length=10)),
            ],
        ),
    ]
