# Generated by Django 3.0.1 on 2020-03-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='site_type',
            field=models.CharField(choices=[('COMMERCIAL', 'COMMERCIAL'), ('OFFICE', 'OFFICE'), ('HOME', 'HOME')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='source_type',
            field=models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], default='', max_length=10),
        ),
    ]
