# Generated by Django 3.0.1 on 2020-03-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='labour',
            name='full_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='labour',
            name='mobile_number',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='labour',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='full_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='mobile_number',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='vendor',
            name='full_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='vendor',
            name='mobile_number',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='vendor',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
