# Generated by Django 3.0.1 on 2020-03-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='client',
            name='full_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='client',
            name='mobile_number',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='client',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='site_type',
            field=models.CharField(choices=[('COMMERCIAL', 'COMMERCIAL'), ('OFFICE', 'OFFICE'), ('HOME', 'HOME')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='source_type',
            field=models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='lead',
            name='full_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='lead',
            name='mobile_number',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='lead',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='site_type',
            field=models.CharField(choices=[('COMMERCIAL', 'COMMERCIAL'), ('OFFICE', 'OFFICE'), ('HOME', 'HOME')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='source_type',
            field=models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='prospect',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='prospect',
            name='full_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='prospect',
            name='mobile_number',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='prospect',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prospect',
            name='site_type',
            field=models.CharField(choices=[('COMMERCIAL', 'COMMERCIAL'), ('OFFICE', 'OFFICE'), ('HOME', 'HOME')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prospect',
            name='source_type',
            field=models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], default='', max_length=10),
        ),
    ]
