# Generated by Django 3.0.1 on 2020-03-31 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CivilMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(blank=True, default='', max_length=12)),
                ('particulars', models.CharField(blank=True, default='', max_length=500)),
                ('quantity', models.CharField(blank=True, default='', max_length=100)),
                ('unit', models.CharField(blank=True, default='', max_length=100)),
                ('rate', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElectricMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(blank=True, default='', max_length=12)),
                ('particulars', models.CharField(blank=True, default='', max_length=500)),
                ('quantity', models.CharField(blank=True, default='', max_length=100)),
                ('unit', models.CharField(blank=True, default='', max_length=100)),
                ('rate', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaintMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(blank=True, default='', max_length=12)),
                ('particulars', models.CharField(blank=True, default='', max_length=500)),
                ('quantity', models.CharField(blank=True, default='', max_length=100)),
                ('unit', models.CharField(blank=True, default='', max_length=100)),
                ('rate', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlumbingMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(blank=True, default='', max_length=12)),
                ('particulars', models.CharField(blank=True, default='', max_length=500)),
                ('quantity', models.CharField(blank=True, default='', max_length=100)),
                ('unit', models.CharField(blank=True, default='', max_length=100)),
                ('rate', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlyMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(blank=True, default='', max_length=12)),
                ('particulars', models.CharField(blank=True, default='', max_length=500)),
                ('quantity', models.CharField(blank=True, default='', max_length=100)),
                ('unit', models.CharField(blank=True, default='', max_length=100)),
                ('rate', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('unit', models.CharField(default='', max_length=12)),
                ('rate', models.CharField(default='', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='TilesMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(blank=True, default='', max_length=12)),
                ('particulars', models.CharField(blank=True, default='', max_length=500)),
                ('quantity', models.CharField(blank=True, default='', max_length=100)),
                ('unit', models.CharField(blank=True, default='', max_length=100)),
                ('rate', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Service')),
            ],
        ),
    ]
