# Generated by Django 3.0.1 on 2020-03-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0002_auto_20200331_1921'),
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilmaterial',
            name='prospect',
            field=models.ManyToManyField(default='', to='prospect.Prospect'),
        ),
        migrations.AddField(
            model_name='electricmaterial',
            name='prospect',
            field=models.ManyToManyField(default='', to='prospect.Prospect'),
        ),
        migrations.AddField(
            model_name='paintmaterial',
            name='prospect',
            field=models.ManyToManyField(default='', to='prospect.Prospect'),
        ),
        migrations.AddField(
            model_name='plumbingmaterial',
            name='prospect',
            field=models.ManyToManyField(default='', to='prospect.Prospect'),
        ),
        migrations.AddField(
            model_name='plymaterial',
            name='prospect',
            field=models.ManyToManyField(default='', to='prospect.Prospect'),
        ),
        migrations.AddField(
            model_name='service',
            name='prospect',
            field=models.ManyToManyField(default='', to='prospect.Prospect'),
        ),
        migrations.AddField(
            model_name='tilesmaterial',
            name='prospect',
            field=models.ManyToManyField(default='', to='prospect.Prospect'),
        ),
    ]
