# Generated by Django 3.0.1 on 2020-04-02 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0002_auto_20200331_1921'),
        ('database', '0002_auto_20200331_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='civilmaterial',
            name='prospect',
        ),
        migrations.AddField(
            model_name='civilmaterial',
            name='prospect',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='prospect.Prospect'),
        ),
        migrations.RemoveField(
            model_name='electricmaterial',
            name='prospect',
        ),
        migrations.AddField(
            model_name='electricmaterial',
            name='prospect',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='prospect.Prospect'),
        ),
        migrations.RemoveField(
            model_name='paintmaterial',
            name='prospect',
        ),
        migrations.AddField(
            model_name='paintmaterial',
            name='prospect',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='prospect.Prospect'),
        ),
        migrations.RemoveField(
            model_name='plumbingmaterial',
            name='prospect',
        ),
        migrations.AddField(
            model_name='plumbingmaterial',
            name='prospect',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='prospect.Prospect'),
        ),
        migrations.RemoveField(
            model_name='plymaterial',
            name='prospect',
        ),
        migrations.AddField(
            model_name='plymaterial',
            name='prospect',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='prospect.Prospect'),
        ),
        migrations.RemoveField(
            model_name='tilesmaterial',
            name='prospect',
        ),
        migrations.AddField(
            model_name='tilesmaterial',
            name='prospect',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='prospect.Prospect'),
        ),
    ]
