# Generated by Django 3.0.1 on 2020-04-02 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0002_auto_20200331_1921'),
        ('database', '0003_auto_20200402_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='prospect',
        ),
        migrations.AddField(
            model_name='service',
            name='prospect',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='prospect.Prospect'),
        ),
    ]
